---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - lan_network != ""
      - redis_version != ""
      - redis_overlay_network != ""
      - redis_sentinel_quorum != ""
      - redis_server_hosts != ""
      - redis_sentinel_hosts != ""
      - docker_redis_config_location != ""
      - docker_redis_server_conf_template != ""
      - docker_redis_sentinel_conf_template != ""
      - docker_redis_server_sh != ""
      - docker_redis_sentinel_sh != ""

- name: Include Redis tasks
  include_tasks: redis.yml
